theme: osuny
_merge: deep
params:
  plausible: afalab.org
  logo:
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: after-hero
  summary:
    position: content
  search: 
    active: true
    positions:
      - primary
      - footer
  organizations:
    single:
      backlinks: true
  projects:
    index:
      layout: list
  posts:
    index:
      layout: grid