theme: osuny
_merge: deep
params:
  plausible: afalab.org
  logo:
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: after-hero
  summary:
    position: content
  search: 
    active: true
    positions:
      - primary
      - footer
  organizations:
    single:
      backlinks: true
  projects:
    index:
      layout: list
  posts:
    index:
      layout: list
  menu:
    primary:
      level_1:
        summary:
          active: false
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
      level_2:
        summary:
          active: false
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
        title:
          active: false
          summary:
            active: false
            source: "Summary" # "Summary" | "meta_description"
            truncate: 125