theme: osuny
_merge: deep
params:
  debug:
    productionUrl: https://www.afalab.org
  plausible: afalab.org
  logo:
    footer: "/assets/images/logo.svg"
  search: 
    active: true
    positions:
      - primary
      - footer
  organizations:
    single:
      backlinks: true
  projects:
    index:
      layout: list
  posts:
    index:
      layout: grid